version: '3'
services:
  spartan.core:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - DEBUG=api
      - NAME=Spartan Core Docker
